Repository authzed/docs, pull requests merged in 2021-11, with the labels that each got.

#4 lint: configure & pass all markdown files
  .markdownlint.yaml
  docs/guides/first-app.md
  docs/guides/schema.md
  docs/reference/api.md
  docs/reference/clients.md
  docs/reference/schema-lang.md
  docs/v0/api.md
  docs/v0/concepts.md
Labels: kind/tech debt, priority/1 high

#8 Nov dependabot updates
  package.json
  yarn.lock
Labels: area/dependencies

#9 guides: first-app updated with v1 (minus Java)
  docs/guides/first-app.md
Labels: kind/tech debt, priority/2 medium

#11 api: add section on gateway
  docs/reference/api.md
Labels: area/spicedb, priority/2 medium

#16 spicedb: add feature overview
  docs/spicedb/feature-overview.md
  sidebars.js
  static/img/arch.svg
Labels: area/spicedb
